import { IActionRow } from './IActionRow';
import { IAnchor } from './IAnchor';
import { IButton } from './IButton';
import { IContainer } from './IContainer';
import { IFormContainer } from './IFormContainer';
import { IFormField } from './IFormField';
import { IFormRow } from './IFormRow';
import { IFormSection } from './IFormSection';
import { IHint } from './IHint';
import { IInput } from './IInput';
import { IInputLabel } from './IInputLabel';
import { IRadio } from './IRadio';
import { ISectionBody } from './ISectionBody';
import { ISectionFooter } from './ISectionFooter';
import { ISectionFooterPrimaryContent } from './ISectionFooterPrimaryContent';
import { ISectionFooterSecondaryContent } from './ISectionFooterSecondaryContent';
import { ISectionHeader } from './ISectionHeader';
import { ISignInButton } from './ISignInButton';
import { ISignInButtonContent } from './ISignInButtonContent';
import { ISignInButtonIcon } from './ISignInButtonIcon';
import { IStrike } from './IStrike';
import { IStrikeContent } from './IStrikeContent';
import { IToast } from './IToast';

export interface IBootstrap {
  container: IContainer;
  formContainer: IFormContainer;
  formField: IFormField;
  formSection: IFormSection;
  sectionHeader: ISectionHeader;
  sectionBody: ISectionBody;
  sectionFooter: ISectionFooter;
  sectionFooterPrimaryContent: ISectionFooterPrimaryContent;
  sectionFooterSecondaryContent: ISectionFooterSecondaryContent;
  input: IInput;
  button: IButton;
  signInButton: ISignInButton;
  signInButtonIcon: ISignInButtonIcon;
  signInButtonContent: ISignInButtonContent;
  formRow: IFormRow;
  strike: IStrike;
  strikeContent: IStrikeContent;
  actionRow: IActionRow;
  a: IAnchor;
  hint: IHint;
  radio: IRadio;
  inputLabel: IInputLabel;
  toast: IToast;
}
